# Generated by Django 4.2.1 on 2023-05-12 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
