# Generated by Django 4.2.1 on 2023-05-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_answer_item_alter_answer_answer_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='answers_per_item',
            field=models.IntegerField(default=3),
        ),
    ]
